name: smart_complaint_tracker
description: A mobile app for tracking and resolving complaints in campus and city.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  provider: ^6.1.2
  flutter_redux: ^0.10.0
  redux: ^5.0.0
