name: smart_complaint_tracker
description: A mobile app for tracking and resolving complaints in campus and city.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.14.0
  provider: ^6.1.2
  flutter_redux: ^0.10.0
  redux: ^5.0.0
